# Numpy

In [4]:
import numpy as np

In [6]:
a = np.array([1, 2, 3, 4, 5])
b = np.arange(0, 10, 2) #(np.arrange([Starting number], [Less than], [Increment]))
c = np.linspace(0, 1, 5) #(np.linspace([Starting number], [Destination], [Divide into x increments]))
print(f"{a}\n{b}\n{c}")

[1 2 3 4 5]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [7]:
a = np.array([10, 20, 30, 40, 50])
print("Original array", a)

print("Element at index 1: ", a[1])

a[1] = 99
print("Modified array: ", a)

Original array [10 20 30 40 50]
Element at index 1:  20
Modified array:  [10 99 30 40 50]


In [8]:
a = np.array([0, 1, 2, 3, 4, 5, 6])
print(a[2:5])
print(a[:3])
print(a[::2])

[2 3 4]
[0 1 2]
[0 2 4 6]


In [10]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [11]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[0:2, 0:2]) # row 0~2 and column 0~2

print(matrix[1, :]) # row 1 and column 0~2 (:)

print(matrix[:, 1]) # row 0~2 (:) and column 1

[[1 2]
 [4 5]]
[4 5 6]
[2 5 8]


In [13]:
original = np.array([1, 2, 3, 4, 5])

modified = original.copy()

modified[0] = 99

print("Original: ", original)
print("Modified: ", modified)

Original:  [99  2  3  4  5]
Modified:  [99  2  3  4  5]


In [21]:
print(a.shape)
print(a.dtype)
print(a.size)

(7,)
int64
7


In [22]:
three_dimension = np.array([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3,], [1, 2, 3]]])
print(three_dimension.shape)

(2, 2, 3)


In [27]:
print(a)
d = a * 2
e = a + np.array([10])
f = np.array([1, 2, 3])
print(d)
print(e)
print(e * d)
print(d * f) # This will not work
# If you want to multiply arrays together they need to be
# the same shape or dimensions

[0 1 2 3 4 5 6]
[ 0  2  4  6  8 10 12]
[10 11 12 13 14 15 16]
[  0  22  48  78 112 150 192]


In [28]:
f = np.sin(a)
print(f) # "np.sin(a)" pplies sine to each element of a

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155 ]


In [37]:
a = np.arange(12)
print(a)
a_reshaped = a.reshape((3, 4))
print(a_reshaped)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
b = a_reshaped
c = a_reshaped.copy()
print(f"{b}\n{c}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
print("Mean: ", np.mean(matrix, axis=0))
print("Sum: ", np.sum(matrix, axis=0))
print("Std Dev: ", np.std(matrix, axis=0))
print(matrix)

Mean:  [4. 5. 6.]
Sum:  [12 15 18]
Std Dev:  [2.44948974 2.44948974 2.44948974]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Pandas

In [42]:
import pandas as pd
import csv

### Series: A one-dimensional labeled array.

In [43]:
s = pd.Series([10, 20, 30, 40, 50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64


### DataFrame: A two-dimensional labeled data structure with columns of potentially different

In [45]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Salary': [50000, 60000, 70000, 80000]
}
df = pd.DataFrame(data)
print(df)

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    David   40   80000


In [52]:
df = pd.read_csv('customers-100.csv')
print(df.head())

   Index      Customer Id First Name Last Name  \
0      1  DD37Cf93aecA6Dc     Sheryl    Baxter   
1      2  1Ef7b82A4CAAD10    Preston    Lozano   
2      3  6F94879bDAfE5a6        Roy     Berry   
3      4  5Cef8BFA16c5e3c      Linda     Olsen   
4      5  053d585Ab6b3159     Joanna    Bender   

                           Company               City  \
0                  Rasmussen Group       East Leonard   
1                      Vega-Gentry  East Jimmychester   
2                    Murillo-Perry      Isabelborough   
3  Dominguez, Mcmillan and Donovan         Bensonview   
4         Martin, Lang and Andrade     West Priscilla   

                      Country                 Phone 1                Phone 2  \
0                       Chile            229.077.5154       397.884.0519x718   
1                    Djibouti              5153435776       686-620-1820x944   
2         Antigua and Barbuda         +1-539-402-0259    (496)978-3969x58947   
3          Dominican Republic  001-8

In [17]:
print(f"{df.head()}\n\n")
print(f"{df.info()}\n\n")
print(f"{df.describe()}")
df_filtered = df[df['Age'] > 30]
print(df_filtered)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None


        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0
      Name  Age     City
2  Charlie   35  Chicago


In [16]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'City': ['New York', 'Los Angeles', 'Chicago']}
df = pd.DataFrame(data)
names = df['Name']
result_loc = df.loc[0, 'Name'] # "pd.loc[]" is a label based index function
result_iloc = df.iloc[0, 1] # "pd.iloc[]" is an integer based index function

print("Using loc: ", result_loc)
print("Using iloc: ", result_iloc)

Using loc:  Alice
Using iloc:  25


In [58]:
filtered_df = df[df['Age'] > 30]
print(filtered_df)

      Name  Age     City
2  Charlie   35  Chicago


In [63]:
new_row = {"Name": "Unknown", "Age": 0}
df = pd.concat([df, pd.DataFrame([new_row])], ignore_index = True)
print(df)

print(df.isna())

df_filled = df.fillna(0)

df_dropped = df.dropna()

print(df_filled)
print(df_dropped)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3  Unknown    0          NaN
    Name    Age   City
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False   True
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3  Unknown    0            0
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [65]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 25, 40, 30],
    'Salary': [50000, 60000, 55000, 80000, 65000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

grouped = df.groupby('Age')['Salary'].mean()
print("Grouped by Age (Mean Salary):")
print(grouped)

Original DataFrame:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   25   55000
3    David   40   80000
4      Eva   30   65000
Grouped by Age (Mean Salary):
Age
25    52500.0
30    62500.0
40    80000.0
Name: Salary, dtype: float64
